/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#c1ecd4",
        "secondary-container": "#fe7e4f",
        "secondary": "#a43c12",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad6",
        "outline": "#717973",
        "on-primary-fixed": "#002114",
        "surface-bright": "#fbf9f5",
        "inverse-surface": "#30312e",
        "on-secondary": "#ffffff",
        "background": "#fbf9f5",
        "on-tertiary-fixed": "#00201c",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "secondary-fixed": "#ffdbcf",
        "on-primary-fixed-variant": "#274e3d",
        "on-secondary-fixed": "#380c00",
        "on-tertiary-container": "#4bb7a8",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb59c",
        "inverse-primary": "#a5d0b9",
        "on-primary-container": "#86af99",
        "on-tertiary-fixed-variant": "#005048",
        "primary": "#012d1d",
        "tertiary-fixed": "#8cf5e4",
        "on-secondary-container": "#6b1f00",
        "surface": "#fbf9f5",
        "on-surface-variant": "#414844",
        "on-secondary-fixed-variant": "#822800",
        "outline-variant": "#c1c8c2",
        "primary-container": "#1b4332",
        "inverse-on-surface": "#f2f0ed",
        "tertiary": "#002c27",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#6fd8c8",
        "surface-variant": "#e4e2de",
        "on-error-container": "#93000a",
        "on-background": "#1b1c1a",
        "on-surface": "#1b1c1a",
        "surface-container-highest": "#e4e2de",
        "surface-tint": "#3f6653",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a5d0b9",
        "surface-container-low": "#f5f3ef",
        "tertiary-container": "#00443d"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
      }
    },
  },
  plugins: [],
}